# Generated by Django 3.1.1 on 2020-09-26 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0006_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, help_text='Team id', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(help_text='Name of the team', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('winner', models.BooleanField()),
                ('challenge', models.ForeignKey(help_text='Code Jam', on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
