# Generated by Django 3.1.1 on 2020-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timathon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
