# Generated by Django 3.1.1 on 2020-09-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timathon', '0002_auto_20200927_0001'),
        ('timathon', '0002_auto_20200926_2104'),
    ]

    operations = [
    ]
