# Generated by Django 3.1.1 on 2020-10-04 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timathon', '0003_submission_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='voted_by',
            field=models.ManyToManyField(related_name='userwhovotedforteam', to=settings.AUTH_USER_MODEL),
        ),
    ]
