# Generated by Django 3.1.1 on 2020-09-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timathon', '0003_merge_20200927_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(help_text='A Submission ID, automatically generated by Postgres.', primary_key=True, serialize=False)),
                ('github_link', models.URLField(help_text='Link to github repo', max_length=150)),
                ('description', models.TextField(help_text='Project Description', max_length=500)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timathon.team')),
            ],
        ),
    ]
