# Generated by Django 3.1.1 on 2020-10-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timathon', '0005_auto_20201006_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='winner_position',
            new_name='winner',
        ),
    ]
