# Generated by Django 3.1.1 on 2020-10-19 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timathon', '0008_auto_20201006_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='voted_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='userwhovotedforteam', to=settings.AUTH_USER_MODEL),
        ),
    ]
