from django.db import models
from django.contrib.auth.models import User

from TWT.apps.timathon.models import Team


class Submission(models.Model):
    id = models.AutoField(primary_key=True,
                          help_text="A Submission ID, automatically generated by Postgres.")

    github_link = models.URLField(max_length=150, help_text="Link to github repo")

    description = models.TextField(max_length=500, help_text="Project Description")

    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Submission: {self.team}"

