from django.db import models
from django.contrib.auth.models import User
import re
from django.core.validators import RegexValidator
from TWT.apps.timathon.models import Team
from TWT.apps.challenges.models import Challenge

class Submission(models.Model):
    id = models.AutoField(primary_key=True,
                          help_text="A Submission ID, automatically generated by Postgres.")

    github_link = models.CharField(max_length=200, help_text="Link to github repo", validators=[RegexValidator(regex=re.compile(r"https://github.com/[A-Za-z0-9-+_.]*/[A-Za-z0-9.+_-]*"))])

    description = models.TextField(max_length=500, help_text="Project Description")
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Submission: {self.team}"

