# Generated by Django 3.0.6 on 2020-05-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
