# Generated by Django 3.1.1 on 2020-09-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20200926_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
