# Generated by Django 3.1.1 on 2020-09-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.TextField(choices=[('NOT POSTED', 'Not Posted'), ('RUNNING', 'Ongoing'), ('ENDED', 'Ended')], default='NOT POSTED', help_text='The challenge status', max_length=10),
        ),
    ]
