# Generated by Django 3.1.1 on 2020-09-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challenge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='submissions_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='team_creation_status',
            field=models.BooleanField(default=False),
        ),
    ]
