# Generated by Django 3.1.1 on 2020-09-30 21:52

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20200929_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=markdownx.models.MarkdownxField(help_text='A full description of the challenge.', max_length=2000),
        ),
    ]
