# Generated by Django 3.1.1 on 2020-10-03 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0009_challenge_voting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='members_voted',
            field=models.ManyToManyField(related_name='userwhovoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
