# Generated by Django 3.1.1 on 2020-09-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20200930_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(help_text='A full description of the challenge.', max_length=2000),
        ),
    ]
