# Generated by Django 3.1.1 on 2020-10-06 12:19

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_remove_challenge_members_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=martor.models.MartorField(),
        ),
    ]
