# Generated by Django 3.1.1 on 2020-10-09 20:28

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_auto_20201006_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('content', martor.models.MartorField()),
            ],
        ),
    ]
