from django.db import models
from django.contrib.auth.models import User


class Challenge(models.Model):
    id = models.AutoField(primary_key=True,
                          help_text="A challenge ID, automatically generated by Postgres.")

    class ChallengeType(models.TextChoices):
        WEEKLY = 'WE', "Weekly"
        MONTHLY = "MO", "Monthly"

    def __str__(self):
        return f"{self.title} {self.type} Challenge"

    type = models.CharField(
        max_length=2,
        choices=ChallengeType.choices,
        default=ChallengeType.WEEKLY,
        help_text="The type of challenge this is, either weekly(WE) or monthly(MO)."
    )

    title = models.TextField(max_length=25,
                             help_text="The challenge title.")

    short_desc = models.TextField(max_length=100,
                                  help_text="A summary of the full challenge description.")

    description = models.TextField(max_length=2000,
                                   help_text="A full description of the challenge.")

    rules = models.TextField(max_length=512,
                             help_text="A set of rules for this challenge.")

    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               help_text="The challenge author.")
    created_at = models.DateTimeField(auto_now=True)
    posted = models.BooleanField(default=False)
    ended = models.BooleanField(default=False)
    posted_at = models.DateTimeField(null=True, blank=True, default=None)

    @property
    def active(self):
        return self.posted and not self.ended
